local repositorio_vehiculos = require("modules.Lesson 5 - Autonomous Agents.repositorio_vehiculos")

local cantidad_vehiculos = 0
local timer_handle = nil
local iniciado = false

local function random_entre(a, b)
	return a + math.random() * (b - a)
end

local function punto_random_pantalla()
	local w, h = window.get_size()
	return vmath.vector3(
	random_entre(w/2, w/2),
	random_entre(h/2, h/2),
	0
)
end

local function crear_nave(params)
	if (params and params.x and params.y) then
		factory.create("#factory", vmath.vector3(params.x, params.y, 0))
	else
		factory.create("#factory", punto_random_pantalla())
	end
	cantidad_vehiculos = cantidad_vehiculos + 1
	if(cantidad_vehiculos >= 128) then
		timer.cancel(timer_handle)
	end
end

function init(self)
	math.randomseed(os.clock())
	msg.post(".", "acquire_input_focus")
	repositorio_vehiculos.cantidad_maxima = cantidad_vehiculos
end

function on_input(self, action_id, action)
	if (action_id == hash("touch") and action.pressed) then
		crear_nave({ x = action.x, y = action.y })
		if iniciado == false then
			iniciado = true
			timer_handle = timer.delay(0.1, true, crear_nave) 
		end
	end
end
