local vehiculo = require("lessons.lesson 5 - Autonomous Agents.modules.vehiculo")
local steering = require("lessons.lesson 5 - Autonomous Agents.modules.steering")
local repositorio_vehiculos = require("lessons.lesson 5 - Autonomous Agents.modules.repositorio_vehiculos")
local vutil = require("modules.utilidades_vectores")

local function configurar(self)

	self.vehiculo = vehiculo:new({
		id 				= go.get_id(),
		posicion		= go.get_position(),
		velocidad		= vutil.vector_random() * 2,
		aceleracion 	= vmath.vector3(0),
		velocidad_max 	= 2,
		fuerza_max 		= 0.3
	})
	repositorio_vehiculos.agregar(self.vehiculo)
end

local function align(self)
	if (repositorio_vehiculos and repositorio_vehiculos.esta_lleno) then
		local align_steering_table = steering.flocking(self.vehiculo, repositorio_vehiculos,
		{
			separacion = 30,
			separacion_deseado_min = 20,
			separacion_deseado_max = 1000
		})
		self.vehiculo:aplicar_fuerza(align_steering_table.steer)
		if(align_steering_table.en_accion) then
			sprite.play_flipbook("#sprite", "playerShip2_red")
		else
			sprite.play_flipbook("#sprite", "playerShip2_blue")
		end
	end
end

------------------ DEFOLD ------------------
function init(self)
	configurar(self)
end

function update(self, dt)
	self.vehiculo:mover()
	self.vehiculo:girar()
	align(self)
end

function on_message(self, message_id, message)
	if (message_id == hash("configurar")) then
		self.vehiculos = message.vehiculos
	end
end

function on_input(self, action_id, action)
	--obtener_pos_mouse(self, action)
end

