local vehiculo = require("lessons.lesson 5 - Autonomous Agents.modules.vehiculo")
local steering = require("lessons.lesson 5 - Autonomous Agents.modules.steering")

go.property("velocidad", vmath.vector3(0,0,0))

local function configurar(self)
	msg.post(".", "acquire_input_focus")
	self.vehiculo = vehiculo:new({
		posicion = go.get_position(),
		velocidad = vmath.vector3(0),
		aceleracion = vmath.vector3(0),
		velocidad_max = 2.4,
		fuerza_max = 0.1
	})

	self.evade = vmath.vector3(0)
	self.objetivo = vmath.vector3(0)
end

local function actualizar_props(self)
	self.velocidad = self.vehiculo.velocidad
end

local function evade(self)
	self.objetivo = go.get_position("pursue")
	if (vmath.length(self.objetivo - self.vehiculo.posicion) < 100) then
		local velocidad_objetivo = go.get("pursue#pursue", "velocidad")
		self.evade = steering.evade(self.vehiculo, { pos = self.objetivo, vel = velocidad_objetivo })
		self.vehiculo:aplicar_fuerza(self.evade)
	end
end


local function obtener_pos_mouse(self, action)
	self.objetivo.x = action.x
	self.objetivo.y = action.y
end

------------------ DEFOLD ------------------
function init(self)
	configurar(self)
end

function update(self, dt)
	self.vehiculo:mover(self)
	evade(self)
	self.vehiculo:girar(self)
	actualizar_props(self)
end

function on_message(self, message_id, message, sender)

end


function on_input(self, action_id, action)
	--obtener_pos_mouse(self, action)
end
