local vehiculo = require("lessons.lesson 5 - Autonomous Agents.modules.vehiculo")
local steering = require("lessons.lesson 5 - Autonomous Agents.modules.steering")
local repositorio_vehiculos = require("lessons.lesson 5 - Autonomous Agents.modules.repositorio_vehiculos")

local function configurar(self)

	self.vehiculo = vehiculo:new({
		id 				= go.get_id(),
		posicion		= go.get_position(),
		velocidad		= vmath.vector3(0),
		aceleracion 	= vmath.vector3(0),
		velocidad_max 	= 1,
		fuerza_max 		= 0.5
	})
	repositorio_vehiculos.agregar(self.vehiculo)
end

local function separate(self)
	if (repositorio_vehiculos and repositorio_vehiculos.esta_lleno) then
		local separate_steering_table = steering.separate(self.vehiculo, repositorio_vehiculos)
		self.vehiculo:aplicar_fuerza(separate_steering_table.steer * 0.05)
		if(separate_steering_table.en_accion) then
			sprite.play_flipbook("#sprite", "playerShip2_red")
		else
			sprite.play_flipbook("#sprite", "playerShip2_blue")
		end
	end
end

------------------ DEFOLD ------------------
function init(self)
	configurar(self)
end

function update(self, dt)
	self.vehiculo:mover()
	self.vehiculo:girar()
	separate(self)
end

function on_message(self, message_id, message)
	if (message_id == hash("configurar")) then
		self.vehiculos = message.vehiculos
	end
end

function on_input(self, action_id, action)
	--obtener_pos_mouse(self, action)
end

